sudo: required
language: java
services:
- docker
jdk:
- openjdk8
notifications:
  email: false
env:
  global:
  - secure: jDB86/3nITal6cg4oTjYhqaFHVlOx6CZ9iZrW4XzCt1PQrfII5GkKX1mYJL4N/Bqo5ifDPR5nz/JVY1myYfcHKuqp2+7Ygi45kQYa/UGDHmtRveX6Hc+KezyAHdApuyTN2YmyrPOn4N/vTxVgcKexeJ6/gI5QHlQR9UhRd2me8KnPUIk/WPJfVMKBTsV/DKi/aGlM1oWD2ImAvFZLYlNFHX1ld915VGuOzEL/Q40Vl4WBBorDZ9hC+OMvKwo/+1ybKGMOOGq0w0pNvfYr9Neyxkj8bwm4wpI7srWgLmUiVZccaIMQTv578tOK0jc5ZnM3F7mq3PVoux3/giewe5WSsXr8PNSJNXW3jQRlweeLlwavc+3zByIMUFUNLgb5rzEClU3k3Zs4ZX37w9B6m8ee/Nm15b244t0bla+OgMiA1KCviXCAY4jxtRecFGnegAZwL+xd8H6D/xD8wgCSMvkLWeRWe2QV4t6EO2IBO+QRyjKRCnkwRT7/I5Mn+DurB5eHD2oDJbPDm9mxPBuMFfEaa3rgTMNVrGd6+PLmF1QcvtRzUYjWbEceI3nZB+tbShdcVI0DYZnperWv6mrR/BnBg3CtoDLzZPHa8uBJXKpM0eTmKlVQY1epA0xerYcD1Mjhx2BKtToggCroZU8b+vZlaGLds4Dbeop9DY9eyerEO8=
  - secure: REe9d1uOExJFdsmRv+MIS2dQK5IuJFZjpm15+c48RvCtAGRtckrX6NWRlc43KetjCrSJgiRg10xPDALNJwBa29xs2Yil9ibug7ahC/HagOWhjDCV3UdSsonGuQvui7OkQZZKd/3ZcqYUF1G2grT/e0cyfoU8LB86cLjlfl2GmcZa/CYrYh5JTt95GTPBlCwSzZ+P5uNn6Ws0MX/uHKSDRMarTGuloAsEk7xd2UHE3a1YFtTNSUJLkr6Bre7fVPO17z7iyojUP7R3Z2yfemoRXz5aARwDb6AsK1fMB319XhZsPkJ6VTukETEtNB1Eub2cPkKCoP49ePduLJlAKNPuS8xs8o+FONy7+UZc8L8yYLDtcs9/7D9US5U+40yO0nWKe83NYifhgN/b58YoUDm/U3EzbccY3B+aplvs0DI97xi7RMSCcy6p1lG2+l5d9TiZwVJOTUkMHpD27KRjvCN23bv5VYMV8f7eTeWYNfQim3RYRccsj+9BaVwwW/YbzdaL3K5ivIaOB0w1lZiGC6oX7VnA/tNdCblkOdAHtR1eOLrD8Cz/WC60StS6Iq4C8W4hggQPPWhA+TkMWCkupU7RTPBxQ9f/f6sXbOA+BpDM0BWfBpmzuMjKm/b3g6JDfCxHtMF0gso4sipITxg7x91ZkOsSdbRJTOFf8XPwsXjkr0Q=
script: ".travis/build_script.sh"
after_success: ".travis/push_script.sh"
